name: Spider Jar Gen CI
on:

  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
          
       #- name: Updates spider json to xytv
        #run: | 
          #git clone https://github.com/xinyi1984/xytv 
          #rm -r xytv/json/adult.json 
          #mv ./json/adult.json xytv/json/
          #cd xytv
          #git config --global user.name "github-actions[bot]"
          #git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          #git add json/
          #git remote rm origin
          #git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
          #git commit -m "更新jar/json"
          #git push -f -u origin master
    
      - name: Build with Gradle
        run: ./buildAndGenJar.bat ec
      
      - name: Update spider jar
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'update spider jar'
          add: "['./jar/custom_spider.jar', './jar/custom_spider.jar.md5']"
